spring.application.name=PatientRecordApplication
spring.datasource.url=jdbc:mysql://localhost:3306/patient_db
spring.datasource.username=root
spring.datasource.password=Helloarie@999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
